openapi: 3.0.0
info:
  title: OpenWeatherMap API
  version: '1.0'
  description: 'Get the current weather, daily forrcast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this-day-in-history charts are available for your reference. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `currennt` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` paramater) will provide the most precise location results.'
  contact:
    name: OpenWeatherMap API
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: Your GET endpoint
      tags:
        - weatherendpoint
      responses: {}
      operationId: get-weather
      security:
        - app_id: []
      parameters:
        - schema:
            type: integer
          in: query
          name: zip
          description: Postal code of the city of your interest.
components:
  schemas: {}
  securitySchemes:
    app_id:
      name: appid
      type: apiKey
      in: query
